/**
 * The seed catalogue.
 *
 * Forty-six garments from fourteen wardrobes. Every one has a real brand, a
 * plausible price for its category in this market, measurements, care notes and
 * a description written the way an owner would write it — because a marketplace
 * populated with "Product 1" tells you nothing about whether the interface
 * works.
 *
 * Prices are in paise. Measurements are in millimetres.
 */

export type SeedFulfilment = "PICKUP" | "LOCAL_DELIVERY" | "SHIPPING";

export interface SeedGarment {
  readonly slug: string;
  readonly title: string;
  readonly brand: string;
  readonly category: string;
  readonly size: string;
  readonly color: string;
  readonly gender: "WOMEN" | "MEN" | "UNISEX";
  readonly condition: "NEW_WITH_TAGS" | "LIKE_NEW" | "GENTLY_WORN" | "WELL_LOVED";
  readonly owner: string;
  readonly description: string;
  readonly fabric: string;
  readonly care: string;
  readonly retailMinor: number;
  readonly measurements?: {
    bustMm?: number;
    waistMm?: number;
    hipMm?: number;
    lengthMm?: number;
    shoulderMm?: number;
    sleeveMm?: number;
  };

  readonly baseRateMinor: number;
  readonly baseDurationDays: number;
  readonly extraDayRateMinor: number;
  readonly depositMinor: number;
  readonly cleaningFeeMinor?: number;

  readonly minRentalDays?: number;
  readonly maxRentalDays?: number;
  readonly bufferDays?: number;
  readonly leadTimeDays?: number;
  readonly instantBook?: boolean;

  readonly fulfilment: readonly SeedFulfilment[];
  readonly deliveryFeeMinor?: number;
  readonly occasions: readonly string[];
  readonly terms?: string;

  /** Appears in the homepage rail. */
  readonly trending?: boolean;
  readonly rentalCount: number;
  readonly ratingAvgBps: number;
  readonly ratingCount: number;
}

export const SEED_GARMENTS: readonly SeedGarment[] = [
  // ── Meher Kapadia · Vadodara — inherited saris and handloom ───────────────
  {
    slug: "vintage-silk-saree-in-claret",
    title: "Vintage silk saree in claret",
    brand: "unbranded",
    category: "sarees",
    size: "free-size",
    color: "claret",
    gender: "WOMEN",
    condition: "GENTLY_WORN",
    owner: "meher-kapadia",
    description:
      "My grandmother's, bought in Surat sometime in the seventies and worn to every wedding since. The silk has softened in the way only age does — it falls rather than holds. Zari border is intact throughout; there is one small darn on the inner pleat that has never once been visible when worn.",
    fabric: "Mulberry silk with real zari border",
    care: "Dry clean only. Please do not pin through the border.",
    retailMinor: 4_500_00,
    measurements: { lengthMm: 5_500 },
    baseRateMinor: 850_00,
    baseDurationDays: 3,
    extraDayRateMinor: 200_00,
    depositMinor: 2_000_00,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["wedding", "traditional", "festive"],
    terms: "Comes with the original petticoat and a fall already stitched. Blouse not included.",
    trending: true,
    rentalCount: 14,
    ratingAvgBps: 49000,
    ratingCount: 12,
  },
  {
    slug: "banarasi-tissue-saree-old-gold",
    title: "Banarasi tissue saree in old gold",
    brand: "unbranded",
    category: "sarees",
    size: "free-size",
    color: "old-gold",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "meher-kapadia",
    description:
      "Tissue this fine catches every bit of light in a room, which is either the point or a problem depending on the event. Worn twice. The gold is genuine zari and has not dulled.",
    fabric: "Silk tissue, handwoven in Varanasi",
    care: "Dry clean. Store flat, not on a hanger — tissue creases at the fold.",
    retailMinor: 6_800_00,
    measurements: { lengthMm: 5_500 },
    baseRateMinor: 1_400_00,
    baseDurationDays: 3,
    extraDayRateMinor: 350_00,
    depositMinor: 4_000_00,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["wedding", "festive", "traditional"],
    rentalCount: 9,
    ratingAvgBps: 50000,
    ratingCount: 8,
  },
  {
    slug: "linen-saree-in-indigo",
    title: "Linen saree in indigo",
    brand: "anavila",
    category: "sarees",
    size: "free-size",
    color: "indigo",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "meher-kapadia",
    description:
      "The one I recommend to anyone wearing a saree for the first time. Linen holds its own pleats, so you are not fighting it all evening. Reads formal enough for a registry wedding and casual enough for a gallery opening.",
    fabric: "Handwoven linen",
    care: "Dry clean preferred. Light steam only.",
    retailMinor: 2_200_00,
    measurements: { lengthMm: 5_500 },
    baseRateMinor: 700_00,
    baseDurationDays: 3,
    extraDayRateMinor: 175_00,
    depositMinor: 1_500_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["formal", "office", "traditional"],
    trending: true,
    rentalCount: 21,
    ratingAvgBps: 48000,
    ratingCount: 17,
  },
  {
    slug: "chanderi-saree-in-sage",
    title: "Chanderi saree in sage",
    brand: "raw-mango",
    category: "sarees",
    size: "free-size",
    color: "sage",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "meher-kapadia",
    description:
      "Bought for a daytime wedding in Jaipur and it was exactly right — chanderi is light enough for heat but has enough body to photograph well. Sage is a difficult colour to find and an easy one to wear.",
    fabric: "Silk-cotton chanderi",
    care: "Dry clean only.",
    retailMinor: 3_400_00,
    baseRateMinor: 1_100_00,
    baseDurationDays: 3,
    extraDayRateMinor: 250_00,
    depositMinor: 2_500_00,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["wedding", "festive", "traditional"],
    rentalCount: 7,
    ratingAvgBps: 50000,
    ratingCount: 6,
  },

  // ── Ananya Desai · Mumbai — the stylist's wedding edit ────────────────────
  {
    slug: "black-satin-midi-dress",
    title: "Black satin midi dress",
    brand: "reformation",
    category: "dresses",
    size: "s",
    color: "black",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "ananya-desai",
    description:
      "Bias-cut, which means it moves properly and forgives a large dinner. The straps are adjustable — I am 5'4\" and wore it without alteration, but there is room to take it up.",
    fabric: "Viscose satin, fully lined",
    care: "Dry clean. Satin marks with water, so please keep it away from ice buckets.",
    retailMinor: 24_000_00,
    measurements: { bustMm: 870, waistMm: 700, hipMm: 920, lengthMm: 1_240 },
    baseRateMinor: 1_200_00,
    baseDurationDays: 3,
    extraDayRateMinor: 300_00,
    depositMinor: 3_500_00,
    instantBook: true,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["party", "date-night", "formal"],
    trending: true,
    rentalCount: 28,
    ratingAvgBps: 49000,
    ratingCount: 24,
  },
  {
    slug: "ivory-sequinned-gown",
    title: "Ivory sequinned gown",
    brand: "amit-aggarwal",
    category: "gowns",
    size: "m",
    color: "ivory",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "ananya-desai",
    description:
      "The single most expensive thing I own and the one I have worn least. Structured bodice, and the sequin work is hand-applied on a stretch base so it moves with you rather than against you. Needs heels — the hem is cut for them.",
    fabric: "Hand-embellished sequins on stretch crepe",
    care: "Specialist dry clean only. I handle the cleaning myself after each rental.",
    retailMinor: 185_000_00,
    measurements: { bustMm: 900, waistMm: 740, hipMm: 960, lengthMm: 1_520 },
    baseRateMinor: 6_500_00,
    baseDurationDays: 3,
    extraDayRateMinor: 1_500_00,
    depositMinor: 25_000_00,
    cleaningFeeMinor: 800_00,
    minRentalDays: 3,
    maxRentalDays: 7,
    bufferDays: 2,
    leadTimeDays: 3,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY"],
    deliveryFeeMinor: 400_00,
    occasions: ["wedding", "formal", "party"],
    terms:
      "Collection in person only, and I would like to meet you first. Fittings welcome in the week before.",
    rentalCount: 6,
    ratingAvgBps: 50000,
    ratingCount: 6,
  },
  {
    slug: "emerald-velvet-anarkali",
    title: "Emerald velvet anarkali",
    brand: "sabyasachi",
    category: "anarkalis",
    size: "m",
    color: "emerald",
    gender: "WOMEN",
    condition: "GENTLY_WORN",
    owner: "ananya-desai",
    description:
      "Winter wedding armour. Velvet, so genuinely warm — I would not wear this in Chennai in May. The gold work at the neckline is dense and heavy, and the skirt takes a full turn without effort.",
    fabric: "Silk velvet with zardozi neckline",
    care: "Dry clean only. Hang immediately after wearing.",
    retailMinor: 145_000_00,
    measurements: { bustMm: 920, waistMm: 780, lengthMm: 1_420 },
    baseRateMinor: 5_200_00,
    baseDurationDays: 3,
    extraDayRateMinor: 1_200_00,
    depositMinor: 20_000_00,
    cleaningFeeMinor: 600_00,
    bufferDays: 2,
    leadTimeDays: 2,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY"],
    deliveryFeeMinor: 400_00,
    occasions: ["wedding", "festive", "traditional"],
    trending: true,
    rentalCount: 11,
    ratingAvgBps: 49000,
    ratingCount: 10,
  },
  {
    slug: "blush-organza-lehenga",
    title: "Blush organza lehenga",
    brand: "anita-dongre",
    category: "lehengas",
    size: "s",
    color: "blush",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "ananya-desai",
    description:
      "Bought for a mehendi and worn once. Organza is light, which matters when the function runs eight hours. Comes as skirt, blouse and dupatta; the blouse has a back tie so there is some flexibility in fit.",
    fabric: "Organza with resham thread work",
    care: "Dry clean only. Organza catches on jewellery — please be careful with kadas.",
    retailMinor: 96_000_00,
    measurements: { bustMm: 860, waistMm: 700, lengthMm: 1_050 },
    baseRateMinor: 4_200_00,
    baseDurationDays: 3,
    extraDayRateMinor: 950_00,
    depositMinor: 15_000_00,
    cleaningFeeMinor: 500_00,
    leadTimeDays: 2,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
    deliveryFeeMinor: 350_00,
    occasions: ["wedding", "festive"],
    rentalCount: 13,
    ratingAvgBps: 48000,
    ratingCount: 11,
  },
  {
    slug: "printed-silk-slip-dress",
    title: "Printed silk slip dress",
    brand: "masaba",
    category: "dresses",
    size: "m",
    color: "saffron",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "ananya-desai",
    description:
      "The print is the whole outfit — wear it with nothing else going on. Silk, so it packs to nothing, which has made it my most travelled dress.",
    fabric: "Printed crepe silk",
    care: "Dry clean.",
    retailMinor: 28_000_00,
    measurements: { bustMm: 900, waistMm: 760, hipMm: 960, lengthMm: 1_180 },
    baseRateMinor: 1_400_00,
    baseDurationDays: 3,
    extraDayRateMinor: 350_00,
    depositMinor: 4_000_00,
    instantBook: true,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["vacation", "party", "date-night"],
    rentalCount: 17,
    ratingAvgBps: 47000,
    ratingCount: 14,
  },
  {
    slug: "structured-ivory-blazer",
    title: "Structured ivory blazer",
    brand: "theory",
    category: "blazers",
    size: "s",
    color: "ivory",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "ananya-desai",
    description:
      "Sharp shoulder, single button, and it does most of the work in a photograph. I have worn this over a saree more often than over trousers.",
    fabric: "Wool blend, viscose lining",
    care: "Dry clean.",
    retailMinor: 42_000_00,
    measurements: { bustMm: 900, shoulderMm: 390, sleeveMm: 590, lengthMm: 680 },
    baseRateMinor: 1_100_00,
    baseDurationDays: 3,
    extraDayRateMinor: 275_00,
    depositMinor: 4_000_00,
    instantBook: true,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["office", "formal", "party"],
    rentalCount: 19,
    ratingAvgBps: 48000,
    ratingCount: 16,
  },

  // ── Rohan Mehta · Bengaluru — the weekend wardrobe ────────────────────────
  {
    slug: "charcoal-wool-overcoat",
    title: "Charcoal wool overcoat",
    brand: "massimo-dutti",
    category: "jackets",
    size: "l",
    color: "charcoal",
    gender: "MEN",
    condition: "GENTLY_WORN",
    owner: "rohan-mehta",
    description:
      "Three winters in Delhi and one in London. The wool has pilled very slightly under the arms — invisible when worn, but I would rather say so. Cut long, falls to mid-thigh on someone around six foot.",
    fabric: "Wool-cashmere blend",
    care: "Dry clean. Brush down after wearing.",
    retailMinor: 34_000_00,
    measurements: { bustMm: 1_100, shoulderMm: 470, sleeveMm: 650, lengthMm: 1_000 },
    baseRateMinor: 1_300_00,
    baseDurationDays: 3,
    extraDayRateMinor: 300_00,
    depositMinor: 5_000_00,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 250_00,
    occasions: ["formal", "office", "casual"],
    rentalCount: 8,
    ratingAvgBps: 48000,
    ratingCount: 7,
  },
  {
    slug: "black-leather-biker-jacket",
    title: "Black leather biker jacket",
    brand: "allsaints",
    category: "jackets",
    size: "m",
    color: "black",
    gender: "UNISEX",
    condition: "WELL_LOVED",
    owner: "rohan-mehta",
    description:
      "Genuinely broken in, which is the only state worth wearing leather in. Some scuffing at the cuffs and the left elbow. If you want a pristine jacket this is not it; if you want one that looks like you have owned it for years, it is.",
    fabric: "Sheep leather, cupro lining",
    care: "Leather specialist only. Do not dry clean conventionally.",
    retailMinor: 48_000_00,
    measurements: { bustMm: 1_020, shoulderMm: 440, sleeveMm: 630, lengthMm: 640 },
    baseRateMinor: 1_500_00,
    baseDurationDays: 3,
    extraDayRateMinor: 350_00,
    depositMinor: 6_000_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 250_00,
    occasions: ["party", "casual", "date-night"],
    trending: true,
    rentalCount: 22,
    ratingAvgBps: 49000,
    ratingCount: 19,
  },
  {
    slug: "navy-single-breasted-suit",
    title: "Navy single-breasted suit",
    brand: "massimo-dutti",
    category: "suits",
    size: "uk-40",
    color: "indigo",
    gender: "MEN",
    condition: "LIKE_NEW",
    owner: "rohan-mehta",
    description:
      'Bought for interviews, kept for weddings. Trousers are unhemmed at 34" inseam so a tailor can take them where you need — I will cover the alteration if you use my tailor in Indiranagar.',
    fabric: "Italian wool, half-canvassed",
    care: "Dry clean.",
    retailMinor: 52_000_00,
    measurements: { bustMm: 1_020, waistMm: 840, shoulderMm: 450, sleeveMm: 640 },
    baseRateMinor: 2_200_00,
    baseDurationDays: 3,
    extraDayRateMinor: 500_00,
    depositMinor: 8_000_00,
    leadTimeDays: 3,
    fulfilment: ["PICKUP"],
    occasions: ["formal", "wedding", "office"],
    terms: "Collection only. I would rather fit it on you than post it and hope.",
    rentalCount: 10,
    ratingAvgBps: 48000,
    ratingCount: 9,
  },
  {
    slug: "olive-field-jacket",
    title: "Olive field jacket",
    brand: "cos",
    category: "jackets",
    size: "l",
    color: "olive",
    gender: "UNISEX",
    condition: "GENTLY_WORN",
    owner: "rohan-mehta",
    description:
      "Four pockets, all of them useful. Cotton canvas that has faded slightly at the shoulders in the way this fabric is supposed to.",
    fabric: "Cotton canvas",
    care: "Machine wash cold, hang dry. No dry cleaning needed.",
    retailMinor: 18_000_00,
    measurements: { bustMm: 1_100, shoulderMm: 480, sleeveMm: 640, lengthMm: 740 },
    baseRateMinor: 750_00,
    baseDurationDays: 3,
    extraDayRateMinor: 175_00,
    depositMinor: 2_000_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["casual", "vacation"],
    rentalCount: 15,
    ratingAvgBps: 47000,
    ratingCount: 12,
  },
  {
    slug: "cream-linen-shirt",
    title: "Cream linen shirt",
    brand: "fabindia",
    category: "shirts",
    size: "l",
    color: "ivory",
    gender: "MEN",
    condition: "GENTLY_WORN",
    owner: "rohan-mehta",
    description:
      "The most useful thing in the wardrobe and the least interesting to write about. Linen, so it will crease — that is the fabric working, not a fault.",
    fabric: "Pure linen",
    care: "Machine wash cold. Iron damp.",
    retailMinor: 3_200_00,
    measurements: { bustMm: 1_080, shoulderMm: 460, sleeveMm: 620, lengthMm: 760 },
    baseRateMinor: 450_00,
    baseDurationDays: 3,
    extraDayRateMinor: 100_00,
    depositMinor: 800_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["casual", "vacation", "office"],
    rentalCount: 12,
    ratingAvgBps: 46000,
    ratingCount: 9,
  },

  // ── Kabir Sharma · Delhi ─────────────────────────────────────────────────
  {
    slug: "black-raw-silk-sherwani",
    title: "Black raw silk sherwani",
    brand: "tarun-tahiliani",
    category: "sherwanis",
    size: "uk-40",
    color: "black",
    gender: "MEN",
    condition: "LIKE_NEW",
    owner: "kabir-sharma",
    description:
      "Worn to my brother's wedding and then to precisely nothing. Black rather than the usual cream or gold, which I would recommend if you are attending rather than starring. Comes with the churidar and a matching stole.",
    fabric: "Raw silk with tonal thread work",
    care: "Dry clean only.",
    retailMinor: 88_000_00,
    measurements: { bustMm: 1_040, waistMm: 880, shoulderMm: 460, sleeveMm: 640, lengthMm: 1_080 },
    baseRateMinor: 3_800_00,
    baseDurationDays: 3,
    extraDayRateMinor: 900_00,
    depositMinor: 15_000_00,
    cleaningFeeMinor: 500_00,
    leadTimeDays: 3,
    bufferDays: 2,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY"],
    deliveryFeeMinor: 400_00,
    occasions: ["wedding", "festive", "traditional"],
    terms: "Please book at least a week ahead so there is time for alterations if you need them.",
    trending: true,
    rentalCount: 9,
    ratingAvgBps: 49000,
    ratingCount: 8,
  },
  {
    slug: "ivory-bandhgala-jacket",
    title: "Ivory bandhgala jacket",
    brand: "antar-agni",
    category: "blazers",
    size: "uk-40",
    color: "ivory",
    gender: "MEN",
    condition: "LIKE_NEW",
    owner: "kabir-sharma",
    description:
      "Wears equally well over a kurta or over trousers and a shirt, which is why it has earned its place. The collar is stiff enough to hold without being uncomfortable.",
    fabric: "Cotton-silk blend",
    care: "Dry clean.",
    retailMinor: 42_000_00,
    measurements: { bustMm: 1_040, shoulderMm: 460, sleeveMm: 640, lengthMm: 780 },
    baseRateMinor: 1_800_00,
    baseDurationDays: 3,
    extraDayRateMinor: 450_00,
    depositMinor: 6_000_00,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
    deliveryFeeMinor: 250_00,
    occasions: ["wedding", "festive", "formal"],
    rentalCount: 11,
    ratingAvgBps: 48000,
    ratingCount: 10,
  },
  {
    slug: "charcoal-nehru-jacket",
    title: "Charcoal Nehru jacket",
    brand: "good-earth",
    category: "blazers",
    size: "m",
    color: "charcoal",
    gender: "MEN",
    condition: "GENTLY_WORN",
    owner: "kabir-sharma",
    description:
      "The thing I reach for when an event is described as 'Indian formal' and nobody will explain what that means.",
    fabric: "Wool blend",
    care: "Dry clean.",
    retailMinor: 12_000_00,
    measurements: { bustMm: 1_000, shoulderMm: 450, lengthMm: 720 },
    baseRateMinor: 700_00,
    baseDurationDays: 3,
    extraDayRateMinor: 175_00,
    depositMinor: 2_000_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["festive", "formal", "office"],
    rentalCount: 16,
    ratingAvgBps: 47000,
    ratingCount: 13,
  },
  {
    slug: "black-wool-tuxedo",
    title: "Black wool tuxedo",
    brand: "theory",
    category: "suits",
    size: "uk-40",
    color: "black",
    gender: "MEN",
    condition: "LIKE_NEW",
    owner: "kabir-sharma",
    description:
      "Satin peak lapel, one button. Bought for a black-tie evening that got cancelled, so it has genuinely been worn once. Bow tie included, cummerbund is not.",
    fabric: "Wool with satin facings",
    care: "Dry clean.",
    retailMinor: 68_000_00,
    measurements: { bustMm: 1_020, waistMm: 850, shoulderMm: 455, sleeveMm: 640 },
    baseRateMinor: 2_800_00,
    baseDurationDays: 3,
    extraDayRateMinor: 650_00,
    depositMinor: 10_000_00,
    leadTimeDays: 2,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY"],
    deliveryFeeMinor: 350_00,
    occasions: ["formal", "party"],
    rentalCount: 5,
    ratingAvgBps: 50000,
    ratingCount: 5,
  },

  // ── Priya Raghunathan · Chennai ──────────────────────────────────────────
  {
    slug: "kanjivaram-saree-in-bottle-green",
    title: "Kanjivaram saree in bottle green",
    brand: "kanjivaram-atelier",
    category: "sarees",
    size: "free-size",
    color: "bottle-green",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "priya-raghunathan",
    description:
      "Bought directly from the weavers' co-operative in Kanchipuram. Heavy — properly heavy, around 800 grams — which is what a real Kanjivaram weighs and why the drape sits the way it does. Contrast border in crimson with a temple motif.",
    fabric: "Pure mulberry silk with gold zari",
    care: "Dry clean only. Store wrapped in muslin.",
    retailMinor: 42_000_00,
    baseRateMinor: 2_400_00,
    baseDurationDays: 3,
    extraDayRateMinor: 550_00,
    depositMinor: 8_000_00,
    leadTimeDays: 2,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["wedding", "traditional", "festive"],
    trending: true,
    rentalCount: 12,
    ratingAvgBps: 50000,
    ratingCount: 11,
  },
  {
    slug: "mustard-cotton-silk-saree",
    title: "Mustard cotton-silk saree",
    brand: "raw-mango",
    category: "sarees",
    size: "free-size",
    color: "mustard",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "priya-raghunathan",
    description:
      "Mustard is unexpectedly easy to wear and photographs beautifully in daylight. This has a plain body and a woven border, so it does not compete with jewellery.",
    fabric: "Cotton-silk",
    care: "Dry clean.",
    retailMinor: 16_000_00,
    baseRateMinor: 950_00,
    baseDurationDays: 3,
    extraDayRateMinor: 225_00,
    depositMinor: 2_500_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["festive", "office", "traditional"],
    rentalCount: 18,
    ratingAvgBps: 48000,
    ratingCount: 15,
  },
  {
    slug: "terracotta-silk-kurta-set",
    title: "Terracotta silk kurta set",
    brand: "nikasha",
    category: "kurtas",
    size: "m",
    color: "terracotta",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "priya-raghunathan",
    description:
      "Kurta, palazzo and dupatta. The whole set is one colour, which sounds dull and is in fact the reason it works — it lengthens rather than cuts you in half.",
    fabric: "Silk with mirror detailing at the yoke",
    care: "Dry clean.",
    retailMinor: 22_000_00,
    measurements: { bustMm: 940, waistMm: 800, lengthMm: 1_180 },
    baseRateMinor: 1_100_00,
    baseDurationDays: 3,
    extraDayRateMinor: 250_00,
    depositMinor: 3_000_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["festive", "wedding", "traditional"],
    rentalCount: 14,
    ratingAvgBps: 49000,
    ratingCount: 12,
  },
  {
    slug: "powder-blue-tailored-trousers",
    title: "Powder blue tailored trousers",
    brand: "cos",
    category: "trousers",
    size: "in-30",
    color: "powder-blue",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "priya-raghunathan",
    description:
      "Wide leg, high waist, pressed crease. These do more for a plain shirt than a plain shirt deserves.",
    fabric: "Wool blend",
    care: "Dry clean.",
    retailMinor: 9_500_00,
    measurements: { waistMm: 760, hipMm: 980, lengthMm: 1_060 },
    baseRateMinor: 600_00,
    baseDurationDays: 3,
    extraDayRateMinor: 150_00,
    depositMinor: 1_500_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["office", "formal"],
    rentalCount: 9,
    ratingAvgBps: 46000,
    ratingCount: 7,
  },

  // ── Zoya Qureshi · Hyderabad ─────────────────────────────────────────────
  {
    slug: "crimson-bridal-lehenga",
    title: "Crimson bridal lehenga",
    brand: "sabyasachi",
    category: "lehengas",
    size: "m",
    color: "crimson",
    gender: "WOMEN",
    condition: "GENTLY_WORN",
    owner: "zoya-qureshi",
    description:
      "My own wedding lehenga. It is very heavy — around six kilograms with the dupatta — and I want to be honest that you will feel it by hour four. It is also the most beautiful thing I will ever own, and it should not spend the rest of its life in a box.",
    fabric: "Raw silk with zardozi and sequin work",
    care: "Specialist dry clean only, arranged by me between rentals.",
    retailMinor: 320_000_00,
    measurements: { bustMm: 900, waistMm: 720, lengthMm: 1_080 },
    baseRateMinor: 12_000_00,
    baseDurationDays: 3,
    extraDayRateMinor: 2_800_00,
    depositMinor: 50_000_00,
    cleaningFeeMinor: 2_000_00,
    minRentalDays: 2,
    maxRentalDays: 5,
    bufferDays: 3,
    leadTimeDays: 7,
    fulfilment: ["PICKUP"],
    occasions: ["wedding"],
    terms:
      "Collection in person, with a fitting the week before. I will need to meet you and I will ask what the occasion is — not to judge, only because I would like to know where it is going.",
    rentalCount: 3,
    ratingAvgBps: 50000,
    ratingCount: 3,
  },
  {
    slug: "aubergine-velvet-gown",
    title: "Aubergine velvet gown",
    brand: "gaurav-gupta-atelier",
    category: "gowns",
    size: "m",
    color: "aubergine",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "zoya-qureshi",
    description:
      "Draped shoulder, sweeping train. Velvet in this depth of colour reads almost black indoors and clearly purple in daylight, which is a good problem to have.",
    fabric: "Silk velvet",
    care: "Dry clean only. Never fold — always hang.",
    retailMinor: 125_000_00,
    measurements: { bustMm: 900, waistMm: 740, hipMm: 970, lengthMm: 1_560 },
    baseRateMinor: 5_500_00,
    baseDurationDays: 3,
    extraDayRateMinor: 1_300_00,
    depositMinor: 20_000_00,
    cleaningFeeMinor: 700_00,
    bufferDays: 2,
    leadTimeDays: 3,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY"],
    deliveryFeeMinor: 400_00,
    occasions: ["formal", "party", "wedding"],
    rentalCount: 7,
    ratingAvgBps: 49000,
    ratingCount: 6,
  },
  {
    slug: "gold-tissue-sharara-set",
    title: "Gold tissue sharara set",
    brand: "payal-singhal",
    category: "co-ords",
    size: "s",
    color: "old-gold",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "zoya-qureshi",
    description:
      "Short kurta with a full sharara. Made for a sangeet and it moves properly when you dance, which is the only real test.",
    fabric: "Tissue with gota work",
    care: "Dry clean.",
    retailMinor: 68_000_00,
    measurements: { bustMm: 860, waistMm: 700, lengthMm: 1_040 },
    baseRateMinor: 3_200_00,
    baseDurationDays: 3,
    extraDayRateMinor: 750_00,
    depositMinor: 12_000_00,
    leadTimeDays: 2,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
    deliveryFeeMinor: 300_00,
    occasions: ["wedding", "festive", "party"],
    trending: true,
    rentalCount: 10,
    ratingAvgBps: 48000,
    ratingCount: 9,
  },

  // ── Devika Sen · Kolkata — handloom ──────────────────────────────────────
  {
    slug: "jamdani-saree-in-ivory",
    title: "Jamdani saree in ivory",
    brand: "unbranded",
    category: "sarees",
    size: "free-size",
    color: "ivory",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "devika-sen",
    description:
      "Woven in Phulia by a family I have bought from for eleven years. Jamdani is a supplementary weft technique, which means the motifs are woven in rather than printed on — hold it to the light and you can see straight through the ground between them.",
    fabric: "Handwoven cotton jamdani",
    care: "Dry clean, or hand wash cold if you know what you are doing.",
    retailMinor: 14_000_00,
    baseRateMinor: 900_00,
    baseDurationDays: 3,
    extraDayRateMinor: 200_00,
    depositMinor: 2_500_00,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["traditional", "festive", "formal"],
    rentalCount: 13,
    ratingAvgBps: 50000,
    ratingCount: 11,
  },
  {
    slug: "indigo-block-print-kurta",
    title: "Indigo block-print kurta",
    brand: "pero",
    category: "kurtas",
    size: "l",
    color: "indigo",
    gender: "WOMEN",
    condition: "GENTLY_WORN",
    owner: "devika-sen",
    description:
      "Natural indigo, hand block printed, and it has faded a little at the seams over three summers in exactly the way that makes it better.",
    fabric: "Handloom cotton, natural indigo dye",
    care: "Hand wash separately in cold water. Indigo bleeds for the first few washes.",
    retailMinor: 8_500_00,
    measurements: { bustMm: 1_000, lengthMm: 1_100 },
    baseRateMinor: 550_00,
    baseDurationDays: 3,
    extraDayRateMinor: 125_00,
    depositMinor: 1_200_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["casual", "office", "traditional"],
    rentalCount: 20,
    ratingAvgBps: 47000,
    ratingCount: 16,
  },
  {
    slug: "sage-linen-co-ord",
    title: "Sage linen co-ord",
    brand: "anavila",
    category: "co-ords",
    size: "m",
    color: "sage",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "devika-sen",
    description:
      "Shirt and wide trousers in the same washed linen. Works as a set or split across two outfits, which is how I have mostly used it.",
    fabric: "Washed linen",
    care: "Machine wash cold, line dry.",
    retailMinor: 18_000_00,
    measurements: { bustMm: 980, waistMm: 800, lengthMm: 1_040 },
    baseRateMinor: 900_00,
    baseDurationDays: 3,
    extraDayRateMinor: 200_00,
    depositMinor: 2_500_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["vacation", "casual", "office"],
    rentalCount: 11,
    ratingAvgBps: 48000,
    ratingCount: 9,
  },
  {
    slug: "coffee-silk-wrap-skirt",
    title: "Coffee silk wrap skirt",
    brand: "bodice",
    category: "skirts",
    size: "s",
    color: "coffee",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "devika-sen",
    description:
      "Bias-cut, ties at the waist, and adjusts across about two sizes as a result. Ankle length on most people.",
    fabric: "Silk crepe",
    care: "Dry clean.",
    retailMinor: 16_000_00,
    measurements: { waistMm: 720, hipMm: 940, lengthMm: 950 },
    baseRateMinor: 700_00,
    baseDurationDays: 3,
    extraDayRateMinor: 175_00,
    depositMinor: 2_000_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["date-night", "office", "party"],
    rentalCount: 8,
    ratingAvgBps: 47000,
    ratingCount: 6,
  },

  // ── Tara Menon · Kochi ───────────────────────────────────────────────────
  {
    slug: "cobalt-sequinned-mini-dress",
    title: "Cobalt sequinned mini dress",
    brand: "self-portrait",
    category: "dresses",
    size: "s",
    color: "cobalt",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "tara-menon",
    description:
      "A dress with exactly one job and it does it very well. Fully sequinned, lined, and heavier than it looks — which is a good sign in sequins.",
    fabric: "Sequins on mesh, jersey lining",
    care: "Dry clean only.",
    retailMinor: 38_000_00,
    measurements: { bustMm: 860, waistMm: 700, hipMm: 900, lengthMm: 860 },
    baseRateMinor: 1_800_00,
    baseDurationDays: 3,
    extraDayRateMinor: 450_00,
    depositMinor: 6_000_00,
    instantBook: true,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
    deliveryFeeMinor: 250_00,
    occasions: ["party", "date-night"],
    trending: true,
    rentalCount: 24,
    ratingAvgBps: 48000,
    ratingCount: 20,
  },
  {
    slug: "rose-satin-slip-skirt",
    title: "Rose satin slip skirt",
    brand: "zara",
    category: "skirts",
    size: "m",
    color: "rose",
    gender: "WOMEN",
    condition: "GENTLY_WORN",
    owner: "tara-menon",
    description:
      "The workhorse. I have worn this with a t-shirt and with a silk blouse and both were fine.",
    fabric: "Polyester satin",
    care: "Machine wash cold on delicate.",
    retailMinor: 3_500_00,
    measurements: { waistMm: 740, hipMm: 960, lengthMm: 900 },
    baseRateMinor: 400_00,
    baseDurationDays: 3,
    extraDayRateMinor: 100_00,
    depositMinor: 800_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["date-night", "party", "casual"],
    rentalCount: 17,
    ratingAvgBps: 45000,
    ratingCount: 13,
  },
  {
    slug: "ivory-crochet-vacation-dress",
    title: "Ivory crochet vacation dress",
    brand: "mango",
    category: "dresses",
    size: "m",
    color: "ivory",
    gender: "WOMEN",
    condition: "GENTLY_WORN",
    owner: "tara-menon",
    description:
      "Bought for Goa, used in Goa, Varkala and Sri Lanka. Needs something underneath — crochet is crochet.",
    fabric: "Cotton crochet",
    care: "Hand wash cold, dry flat.",
    retailMinor: 5_500_00,
    measurements: { bustMm: 900, waistMm: 780, lengthMm: 1_100 },
    baseRateMinor: 500_00,
    baseDurationDays: 3,
    extraDayRateMinor: 125_00,
    depositMinor: 1_200_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["vacation", "casual"],
    rentalCount: 19,
    ratingAvgBps: 46000,
    ratingCount: 15,
  },
  {
    slug: "black-halter-jumpsuit",
    title: "Black halter jumpsuit",
    brand: "sandro",
    category: "co-ords",
    size: "s",
    color: "black",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "tara-menon",
    description:
      "Solves the what-do-I-wear problem entirely. Wide leg, halter neck, open back. There is no bra that works with this and I have tried.",
    fabric: "Crepe",
    care: "Dry clean.",
    retailMinor: 26_000_00,
    measurements: { bustMm: 860, waistMm: 700, hipMm: 920, lengthMm: 1_460 },
    baseRateMinor: 1_300_00,
    baseDurationDays: 3,
    extraDayRateMinor: 325_00,
    depositMinor: 4_000_00,
    instantBook: true,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
    deliveryFeeMinor: 250_00,
    occasions: ["party", "date-night", "formal"],
    rentalCount: 15,
    ratingAvgBps: 48000,
    ratingCount: 12,
  },

  // ── Sana Kulkarni · Ahmedabad ────────────────────────────────────────────
  {
    slug: "bandhani-silk-dupatta-set",
    title: "Bandhani silk kurta and dupatta",
    brand: "unbranded",
    category: "kurtas",
    size: "m",
    color: "crimson",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "sana-kulkarni",
    description:
      "Real bandhani — tied and dyed by hand in Bhuj, which you can tell because the dots are not perfectly even. Machine-printed imitation is everywhere; this is not that.",
    fabric: "Gajji silk, hand-tied bandhani",
    care: "Dry clean only. Do not iron directly over the tied areas.",
    retailMinor: 24_000_00,
    measurements: { bustMm: 940, lengthMm: 1_140 },
    baseRateMinor: 1_200_00,
    baseDurationDays: 3,
    extraDayRateMinor: 280_00,
    depositMinor: 3_500_00,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["festive", "wedding", "traditional"],
    trending: true,
    rentalCount: 16,
    ratingAvgBps: 49000,
    ratingCount: 14,
  },
  {
    slug: "mirror-work-lehenga-in-saffron",
    title: "Mirror work lehenga in saffron",
    brand: "unbranded",
    category: "lehengas",
    size: "m",
    color: "saffron",
    gender: "WOMEN",
    condition: "GENTLY_WORN",
    owner: "sana-kulkarni",
    description:
      "Navratri clothing, made to be danced in for nine nights. The mirrors are hand-stitched and a few have been replaced over the years — I do this myself and you cannot tell which.",
    fabric: "Cotton with abhla mirror work",
    care: "Dry clean. A mirror occasionally comes loose; please do not worry about it.",
    retailMinor: 32_000_00,
    measurements: { waistMm: 760, lengthMm: 1_020 },
    baseRateMinor: 1_800_00,
    baseDurationDays: 3,
    extraDayRateMinor: 400_00,
    depositMinor: 5_000_00,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 250_00,
    occasions: ["festive", "traditional", "party"],
    rentalCount: 22,
    ratingAvgBps: 48000,
    ratingCount: 18,
  },
  {
    slug: "ajrakh-print-shirt-dress",
    title: "Ajrakh print shirt dress",
    brand: "pero",
    category: "dresses",
    size: "l",
    color: "indigo",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "sana-kulkarni",
    description:
      "Ajrakh is a sixteen-step resist printing process and this piece went through all of them. The rust and indigo come from madder and natural indigo respectively, not from a pigment.",
    fabric: "Ajrakh-printed cotton",
    care: "Hand wash cold. Natural dyes soften with washing rather than fading badly.",
    retailMinor: 14_000_00,
    measurements: { bustMm: 1_020, waistMm: 900, lengthMm: 1_180 },
    baseRateMinor: 750_00,
    baseDurationDays: 3,
    extraDayRateMinor: 175_00,
    depositMinor: 2_000_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["casual", "office", "traditional"],
    rentalCount: 12,
    ratingAvgBps: 47000,
    ratingCount: 10,
  },

  // ── Rhea D'Souza · Mumbai ────────────────────────────────────────────────
  {
    slug: "silver-metallic-slip-dress",
    title: "Silver metallic slip dress",
    brand: "zara",
    category: "dresses",
    size: "s",
    color: "silver-grey",
    gender: "WOMEN",
    condition: "GENTLY_WORN",
    owner: "rhea-dsouza",
    description:
      "New Year's Eve, two years running. Metallic, so it shows every crease — steam it before you go out and it is fine.",
    fabric: "Metallic knit",
    care: "Dry clean. Steam rather than iron.",
    retailMinor: 4_500_00,
    measurements: { bustMm: 860, waistMm: 700, hipMm: 900, lengthMm: 1_000 },
    baseRateMinor: 550_00,
    baseDurationDays: 3,
    extraDayRateMinor: 125_00,
    depositMinor: 1_200_00,
    instantBook: true,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["party", "date-night"],
    rentalCount: 21,
    ratingAvgBps: 45000,
    ratingCount: 16,
  },
  {
    slug: "lilac-organza-blouse",
    title: "Lilac organza blouse",
    brand: "bodice",
    category: "tops",
    size: "m",
    color: "lilac",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "rhea-dsouza",
    description:
      "Sheer, so it needs a slip or a good bralette. The volume in the sleeve is the entire point — do not tuck it in fully.",
    fabric: "Silk organza",
    care: "Dry clean.",
    retailMinor: 12_000_00,
    measurements: { bustMm: 960, shoulderMm: 400, sleeveMm: 600, lengthMm: 620 },
    baseRateMinor: 600_00,
    baseDurationDays: 3,
    extraDayRateMinor: 150_00,
    depositMinor: 1_800_00,
    instantBook: true,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["date-night", "party", "office"],
    rentalCount: 13,
    ratingAvgBps: 47000,
    ratingCount: 10,
  },
  {
    slug: "champagne-slip-gown",
    title: "Champagne slip gown",
    brand: "self-portrait",
    category: "gowns",
    size: "m",
    color: "champagne",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "rhea-dsouza",
    description:
      "Cowl neck, open back, floor length. Deceptively simple and consequently very hard to get wrong.",
    fabric: "Satin-backed crepe",
    care: "Dry clean only.",
    retailMinor: 46_000_00,
    measurements: { bustMm: 900, waistMm: 740, hipMm: 960, lengthMm: 1_500 },
    baseRateMinor: 2_400_00,
    baseDurationDays: 3,
    extraDayRateMinor: 600_00,
    depositMinor: 8_000_00,
    leadTimeDays: 2,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY"],
    deliveryFeeMinor: 300_00,
    occasions: ["formal", "wedding", "party"],
    rentalCount: 9,
    ratingAvgBps: 49000,
    ratingCount: 8,
  },

  // ── Nikhil Reddy · Pune ──────────────────────────────────────────────────
  {
    slug: "sand-linen-suit",
    title: "Sand linen suit",
    brand: "zara",
    category: "suits",
    size: "uk-38",
    color: "sand",
    gender: "MEN",
    condition: "GENTLY_WORN",
    owner: "nikhil-reddy",
    description:
      "Beach wedding suit. Linen creases — that is not a defect and you should stop worrying about it before you arrive.",
    fabric: "Linen-viscose blend",
    care: "Dry clean.",
    retailMinor: 12_000_00,
    measurements: { bustMm: 980, waistMm: 800, shoulderMm: 440, sleeveMm: 630 },
    baseRateMinor: 1_200_00,
    baseDurationDays: 3,
    extraDayRateMinor: 300_00,
    depositMinor: 3_500_00,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 250_00,
    occasions: ["wedding", "vacation", "formal"],
    rentalCount: 6,
    ratingAvgBps: 46000,
    ratingCount: 5,
  },
  {
    slug: "bottle-green-velvet-blazer",
    title: "Bottle green velvet blazer",
    brand: "allsaints",
    category: "blazers",
    size: "uk-40",
    color: "bottle-green",
    gender: "MEN",
    condition: "LIKE_NEW",
    owner: "nikhil-reddy",
    description:
      "The blazer I regret buying and everyone else looks excellent in. Velvet, shawl collar, worn twice.",
    fabric: "Cotton velvet",
    care: "Dry clean. Brush the pile in one direction.",
    retailMinor: 22_000_00,
    measurements: { bustMm: 1_020, shoulderMm: 450, sleeveMm: 640, lengthMm: 740 },
    baseRateMinor: 1_400_00,
    baseDurationDays: 3,
    extraDayRateMinor: 350_00,
    depositMinor: 4_500_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 250_00,
    occasions: ["party", "festive", "formal"],
    trending: true,
    rentalCount: 14,
    ratingAvgBps: 48000,
    ratingCount: 12,
  },
  {
    slug: "white-cotton-kurta-churidar",
    title: "White cotton kurta and churidar",
    brand: "fabindia",
    category: "kurtas",
    size: "l",
    color: "ivory",
    gender: "MEN",
    condition: "GENTLY_WORN",
    owner: "nikhil-reddy",
    description:
      "The default. Every man in this country owns one and most of them are somehow never clean when needed.",
    fabric: "Cotton",
    care: "Machine wash. Starch lightly if you want it crisp.",
    retailMinor: 3_800_00,
    measurements: { bustMm: 1_080, shoulderMm: 470, lengthMm: 1_060 },
    baseRateMinor: 400_00,
    baseDurationDays: 3,
    extraDayRateMinor: 100_00,
    depositMinor: 800_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["festive", "traditional", "casual"],
    rentalCount: 18,
    ratingAvgBps: 45000,
    ratingCount: 14,
  },

  // ── Arjun Malhotra · Chandigarh ──────────────────────────────────────────
  {
    slug: "cream-embroidered-sherwani",
    title: "Cream embroidered sherwani",
    brand: "ritu-kumar",
    category: "sherwanis",
    size: "uk-42",
    color: "ivory",
    gender: "MEN",
    condition: "LIKE_NEW",
    owner: "arjun-malhotra",
    description:
      "One cousin's wedding, 2023. Thread work across the chest and cuffs, cream on cream, so it photographs as texture rather than as pattern. Comes with churidar and stole.",
    fabric: "Silk blend with resham embroidery",
    care: "Dry clean only.",
    retailMinor: 55_000_00,
    measurements: { bustMm: 1_080, waistMm: 920, shoulderMm: 470, sleeveMm: 650, lengthMm: 1_100 },
    baseRateMinor: 2_600_00,
    baseDurationDays: 3,
    extraDayRateMinor: 600_00,
    depositMinor: 10_000_00,
    cleaningFeeMinor: 400_00,
    leadTimeDays: 3,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 350_00,
    occasions: ["wedding", "festive", "traditional"],
    rentalCount: 4,
    ratingAvgBps: 45000,
    ratingCount: 4,
  },
  {
    slug: "rust-silk-bandhgala",
    title: "Rust silk bandhgala",
    brand: "torani",
    category: "blazers",
    size: "uk-42",
    color: "rust",
    gender: "MEN",
    condition: "LIKE_NEW",
    owner: "arjun-malhotra",
    description:
      "Rust is a better colour on more people than they expect. Worn once to a reception in Amritsar.",
    fabric: "Raw silk",
    care: "Dry clean.",
    retailMinor: 32_000_00,
    measurements: { bustMm: 1_080, shoulderMm: 470, sleeveMm: 650, lengthMm: 780 },
    baseRateMinor: 1_600_00,
    baseDurationDays: 3,
    extraDayRateMinor: 400_00,
    depositMinor: 5_000_00,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 250_00,
    occasions: ["wedding", "festive", "formal"],
    rentalCount: 5,
    ratingAvgBps: 46000,
    ratingCount: 4,
  },

  // ── Additional pieces rounding out the filters ───────────────────────────
  {
    slug: "olive-tencel-jumpsuit",
    title: "Olive tencel jumpsuit",
    brand: "suket-dhir",
    category: "co-ords",
    size: "m",
    color: "olive",
    gender: "UNISEX",
    condition: "LIKE_NEW",
    owner: "sana-kulkarni",
    description:
      "Utility cut with a drawstring waist, so it adjusts across a fair range. Deep pockets, which should not be remarkable and somehow is.",
    fabric: "Tencel twill",
    care: "Machine wash cold.",
    retailMinor: 19_000_00,
    measurements: { bustMm: 1_000, waistMm: 840, lengthMm: 1_480 },
    baseRateMinor: 850_00,
    baseDurationDays: 3,
    extraDayRateMinor: 200_00,
    depositMinor: 2_500_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["casual", "vacation", "office"],
    rentalCount: 10,
    ratingAvgBps: 47000,
    ratingCount: 8,
  },
  {
    slug: "black-wool-wide-trousers",
    title: "Black wool wide trousers",
    brand: "theory",
    category: "trousers",
    size: "in-32",
    color: "black",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "rhea-dsouza",
    description:
      "The trousers that make everything above them look more expensive. Full break, pressed crease.",
    fabric: "Wool crepe",
    care: "Dry clean.",
    retailMinor: 21_000_00,
    measurements: { waistMm: 800, hipMm: 1_020, lengthMm: 1_080 },
    baseRateMinor: 650_00,
    baseDurationDays: 3,
    extraDayRateMinor: 150_00,
    depositMinor: 2_000_00,
    instantBook: true,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["office", "formal", "party"],
    rentalCount: 11,
    ratingAvgBps: 47000,
    ratingCount: 9,
  },
  {
    slug: "crimson-crepe-shirt",
    title: "Crimson crepe shirt",
    brand: "massimo-dutti",
    category: "shirts",
    size: "s",
    color: "crimson",
    gender: "WOMEN",
    condition: "GENTLY_WORN",
    owner: "tara-menon",
    description: "A red shirt is a decision. This one has been the right one about eight times.",
    fabric: "Crepe de chine",
    care: "Dry clean or hand wash cold.",
    retailMinor: 7_500_00,
    measurements: { bustMm: 900, shoulderMm: 390, sleeveMm: 600, lengthMm: 640 },
    baseRateMinor: 450_00,
    baseDurationDays: 3,
    extraDayRateMinor: 110_00,
    depositMinor: 1_000_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["office", "date-night", "casual"],
    rentalCount: 14,
    ratingAvgBps: 46000,
    ratingCount: 11,
  },
  {
    slug: "champagne-brocade-blouse",
    title: "Champagne brocade blouse",
    brand: "raw-mango",
    category: "tops",
    size: "s",
    color: "champagne",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "meher-kapadia",
    description:
      "A saree blouse that also works as a top with high-waisted trousers, which is how it earns twice its keep. Brocade woven in Benares.",
    fabric: "Silk brocade",
    care: "Dry clean.",
    retailMinor: 11_000_00,
    measurements: { bustMm: 860, shoulderMm: 370, sleeveMm: 280, lengthMm: 380 },
    baseRateMinor: 550_00,
    baseDurationDays: 3,
    extraDayRateMinor: 130_00,
    depositMinor: 1_500_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 150_00,
    occasions: ["festive", "wedding", "party"],
    rentalCount: 16,
    ratingAvgBps: 48000,
    ratingCount: 13,
  },
  {
    slug: "indigo-denim-jacket",
    title: "Indigo denim jacket",
    brand: "unbranded",
    category: "jackets",
    size: "m",
    color: "indigo",
    gender: "UNISEX",
    condition: "WELL_LOVED",
    owner: "rohan-mehta",
    description:
      "Selvedge denim, worn for six years, faded exactly where I sit and where I bend my arms. Nobody can fake this and plenty have tried.",
    fabric: "14oz selvedge denim",
    care: "Wash rarely, cold, inside out.",
    retailMinor: 14_000_00,
    measurements: { bustMm: 1_040, shoulderMm: 460, sleeveMm: 630, lengthMm: 660 },
    baseRateMinor: 600_00,
    baseDurationDays: 3,
    extraDayRateMinor: 150_00,
    depositMinor: 1_800_00,
    instantBook: true,
    fulfilment: ["PICKUP", "SHIPPING"],
    deliveryFeeMinor: 200_00,
    occasions: ["casual", "vacation"],
    rentalCount: 13,
    ratingAvgBps: 47000,
    ratingCount: 10,
  },
  {
    slug: "powder-blue-anarkali",
    title: "Powder blue anarkali",
    brand: "anita-dongre",
    category: "anarkalis",
    size: "l",
    color: "powder-blue",
    gender: "WOMEN",
    condition: "LIKE_NEW",
    owner: "zoya-qureshi",
    description:
      "Daytime function clothing. Light enough for an outdoor mehendi in April, with just enough work at the hem to not read as plain.",
    fabric: "Georgette with chikankari hem",
    care: "Dry clean.",
    retailMinor: 38_000_00,
    measurements: { bustMm: 1_000, waistMm: 860, lengthMm: 1_440 },
    baseRateMinor: 1_900_00,
    baseDurationDays: 3,
    extraDayRateMinor: 450_00,
    depositMinor: 6_000_00,
    fulfilment: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
    deliveryFeeMinor: 250_00,
    occasions: ["wedding", "festive"],
    rentalCount: 8,
    ratingAvgBps: 48000,
    ratingCount: 7,
  },
];
